import type { NavigationItemDefinition } from "../model/navigation";

export const backofficeNavigation = [
  {
    id: "home",
    label: "Accueil",
    area: "primary",
    href: "/backoffice",
    availability: "available",
    exact: true,
  },
  {
    id: "clients",
    label: "Clients",
    area: "primary",
    href: "/backoffice/clients",
    availability: "available",
  },
  {
    id: "prospecting",
    label: "Prospection",
    area: "primary",
    href: "/backoffice/prospecting",
    availability: "planned",
  },
  {
    id: "conversations",
    label: "Conversations",
    area: "primary",
    href: "/backoffice/conversations",
    availability: "planned",
  },
  {
    id: "performance",
    label: "Performance",
    area: "primary",
    href: "/backoffice/performance",
    availability: "planned",
  },
  {
    id: "integrations",
    label: "Intégrations",
    area: "secondary",
    href: "/backoffice/integrations",
    availability: "planned",
  },
  {
    id: "subscriptions",
    label: "Abonnements",
    area: "secondary",
    href: "/backoffice/subscriptions",
    availability: "planned",
  },
  {
    id: "team",
    label: "Équipe",
    area: "secondary",
    href: "/backoffice/team",
    availability: "planned",
  },
  {
    id: "settings",
    label: "Paramètres",
    area: "secondary",
    href: "/backoffice/settings",
    availability: "planned",
  },
] as const satisfies readonly NavigationItemDefinition[];

export const workspaceNavigation = [
  {
    id: "overview",
    label: "Vue d’ensemble",
    area: "primary",
    href: (workspaceId) => `/backoffice/workspaces/${workspaceId}`,
    availability: "available",
    exact: true,
  },
  {
    id: "configuration",
    label: "Configuration",
    area: "primary",
    href: (workspaceId) => `/backoffice/workspaces/${workspaceId}/configuration`,
    availability: "available",
  },
  {
    id: "learning",
    label: "Apprentissage",
    area: "primary",
    href: (workspaceId) => `/backoffice/workspaces/${workspaceId}/learning`,
    availability: "available",
  },
  {
    id: "prospecting",
    label: "Prospection",
    area: "primary",
    href: (workspaceId) => `/backoffice/workspaces/${workspaceId}/prospecting`,
    availability: "available",
  },
  {
    id: "conversations",
    label: "Conversations",
    area: "primary",
    href: (workspaceId) => `/backoffice/workspaces/${workspaceId}/conversations`,
    availability: "planned",
  },
  {
    id: "performance",
    label: "Performance",
    area: "primary",
    href: (workspaceId) => `/backoffice/workspaces/${workspaceId}/performance`,
    availability: "planned",
  },
  {
    id: "integrations",
    label: "Intégrations",
    area: "secondary",
    href: (workspaceId) => `/backoffice/workspaces/${workspaceId}/integrations`,
    availability: "planned",
  },
  {
    id: "subscription",
    label: "Abonnement",
    area: "secondary",
    href: (workspaceId) => `/backoffice/workspaces/${workspaceId}/subscription`,
    availability: "planned",
  },
] as const satisfies readonly NavigationItemDefinition[];

export const portalNavigation = [
  {
    id: "review",
    label: "À valider",
    area: "primary",
    href: (workspaceId) => `/portal/${workspaceId}`,
    availability: "available",
    exact: true,
  },
  {
    id: "prospects",
    label: "Prospects",
    area: "primary",
    href: (workspaceId) => `/portal/${workspaceId}/prospects`,
    availability: "planned",
  },
  {
    id: "conversations",
    label: "Conversations",
    area: "primary",
    href: (workspaceId) => `/portal/${workspaceId}/conversations`,
    availability: "planned",
  },
  {
    id: "appointments",
    label: "Rendez-vous",
    area: "primary",
    href: (workspaceId) => `/portal/${workspaceId}/appointments`,
    availability: "planned",
  },
  {
    id: "performance",
    label: "Performance",
    area: "primary",
    href: (workspaceId) => `/portal/${workspaceId}/performance`,
    availability: "planned",
  },
  {
    id: "settings",
    label: "Abonnement et paramètres",
    area: "secondary",
    href: (workspaceId) => `/portal/${workspaceId}/settings`,
    availability: "planned",
  },
] as const satisfies readonly NavigationItemDefinition[];
