import type { OnboardingDraft, OnboardingStepId, OnboardingStepStatus } from "./onboarding";

export const emptyOnboardingDraft: OnboardingDraft = {
  company: {
    companyName: "",
    website: "",
    industry: "",
    description: "",
    primaryMarket: "",
    companySize: "",
    primaryContactName: "",
    primaryContactEmail: "",
  },
  offer: {
    offerName: "",
    description: "",
    valueProposition: "",
    problemSolved: "",
    targetCustomer: "",
    priceRange: "",
    evidence: "",
    salesNotes: "",
  },
  target: {
    name: "Cible principale",
    industries: "",
    companySizes: "",
    geographies: "",
    companyTypes: "",
    decisionMakers: "",
    requiredCriteria: "",
    preferredCriteria: "",
    exclusions: "",
  },
  qualification: {
    budget: "",
    authority: "",
    need: "",
    timing: "",
    determiningCriteria: "",
    positiveSignals: "",
    exclusionSignals: "",
  },
  approach: {
    tone: "",
    formality: "",
    positioning: "",
    keyArguments: "",
    evidence: "",
    knownObjections: "",
    possibleAnswers: "",
    forbiddenTopics: "",
    preferredCta: "",
    examples: "",
  },
  tools: { operatingMode: "" },
  training: { principleAcknowledged: false },
  launch: { readyForPreparation: false },
};

export const initialOnboardingStatuses: Record<OnboardingStepId, OnboardingStepStatus> = {
  company: "IN_PROGRESS",
  offer: "NOT_STARTED",
  target: "NOT_STARTED",
  qualification: "NOT_STARTED",
  approach: "NOT_STARTED",
  tools: "NOT_STARTED",
  training: "NOT_STARTED",
  launch: "NOT_STARTED",
};
